import { Component, ChangeDetectorRef, inject, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatProgressBarModule } from '@angular/material/progress-bar';
import { Api, ApiError } from './api';
import * as C from './contracts';
import { UiComponent } from './ui';
import { ChartComponent } from './chart';
@Component({selector:'app-root',standalone:true,imports:[CommonModule,FormsModule,MatButtonModule,MatProgressBarModule,UiComponent,ChartComponent],templateUrl:'./app.html'})
export class AppComponent implements OnInit,OnDestroy {
  api=inject(Api);private cdr=inject(ChangeDetectorRef);view='explore';busy=false;ready=false;error='';notice='';menu=false;
  nav=[{id:'explore',icon:'◎',label:'自我探索',sub:'和自己好好聊聊'},{id:'chronicle',icon:'\u25f7',label:'我的歷程',sub:'每段經歷，都有位置'},{id:'records',icon:'\u25a4',label:'生活紀錄',sub:'收集真實的片刻'},{id:'blogs',icon:'\u270e',label:'我的文章',sub:'把理解留給未來'},{id:'insights',icon:'◇',label:'理解與證據',sub:'讓想法有跡可循'},{id:'reflections',icon:'\u2727',label:'探索成果',sub:'走過的思考，值得留下'},{id:'actions',icon:'↗',label:'行動與回顧',sub:'從一小步開始'}];
  devVisible=new URLSearchParams(location.search).get('dev')==='1';devEmail='demo@example.test';
  records:C.Record[]=[];events:C.Event[]=[];templates:C.EventTemplate[]=[];files:C.File[]=[];insights:C.Insight[]=[];reflections:C.Reflection[]=[];actions:C.Action[]=[];sessions:C.Session[]=[];messages:C.Message[]=[];evidences:C.Evidence[]=[];observations:C.Observation[]=[];usage:C.Usage|null=null;
  recordEditor:(C.RecordCreate & {id?:string;version?:number})|null=null;eventEditor:(C.EventCreate & {id?:string;version?:number})|null=null;
  selectedEvent:C.Event|null=null;slots:C.FileSlot[]=[];filter='all';search='';templateDraft:C.SlotCreate[]|null=null;slotName='';linkRecord='';linkFile='';
  session:C.Session|null=null;message='';streamText='';streamUi:unknown[]=[];streaming=false;stage='';runId='';private streamAbort?:AbortController;
  reflectionEditor:C.Reflection|null=null;unknownText='';actionText='';insightEditor:C.Insight|null=null;actionEditor:C.Action|null=null;newAction='';
  whyItems:C.Evidence[]|null=null;whyObservations:C.Observation[]=[];sourceDetail='';feedbackEditor:{id:string;version:number;decision:C.HypothesisFeedback['decision'];statement:string}|null=null;
  deleteTarget:{kind:string;id?:string;label:string}|null=null;
  get title(){return this.nav.find(n=>n.id===this.view)?.label??'帳號與資料';}
  get cleanFiles(){return this.files.filter(f=>f.status==='CLEAN');}
  get visibleEvents(){return this.events.filter(e=>(!this.search||`${e.title} ${e.description}`.includes(this.search))&&(this.filter!=='no-evidence'||!e.evidence_count)&&(this.filter!=='pending'||(e.total_slots??0)>(e.available_slots??0)));}
  get timeline(){return {grid:{left:30,right:30,top:25,bottom:65},xAxis:{type:'category',data:this.visibleEvents.map(e=>e.started_at??'日期未知'),axisLabel:{rotate:20}},yAxis:{show:false,min:0,max:2},series:[{type:'scatter',symbolSize:18,itemStyle:{color:'#26796e'},data:this.visibleEvents.map(()=>1)}]};}
  get graph(){const nodes=[...this.insights.map(i=>({id:i.id,name:i.statement.slice(0,25),symbolSize:30,itemStyle:{color:i.status==='ACTIVE'?'#277c70':'#9caaa1'}})),...this.evidences.map(e=>({id:e.id,name:e.excerpt.slice(0,20)||'來源已移除',symbolSize:15,itemStyle:{color:'#c18b53'}}))];return {series:[{type:'graph',layout:'force',roam:true,label:{show:true,fontSize:10},force:{repulsion:160},data:nodes,links:this.insights.flatMap(i=>i.evidence_refs.filter(id=>this.evidences.some(e=>e.id===id)).map(id=>({source:i.id,target:id})))}]};}
  async ngOnInit(){try{await this.api.me();await this.load();}catch(e){if(!(e instanceof ApiError && e.status===401))this.error=this.errorText(e);}finally{this.ready=true;this.cdr.markForCheck();}}
  ngOnDestroy(){this.streamAbort?.abort();}
  errorText(e:unknown){return e instanceof ApiError?`${e.message}${e.code==='VERSION_CONFLICT'?'；資料已有更新，請重新開啟後再編輯。':''}${e.traceId?'（追蹤碼 '+e.traceId+'）':''}`:e instanceof Error?e.message:'操作失敗，請再試一次。';}
  async perform(fn:()=>Promise<void>){if(this.busy)return;this.busy=true;this.error='';this.notice='';try{await fn();}catch(e){this.error=this.errorText(e);}finally{this.busy=false;this.cdr.markForCheck();}}
  async load(){const result=await Promise.all([this.api.page<C.Record>(this.view==='blogs'?'/blogs':'/records'),this.api.page<C.Event>('/events'),this.api.page<C.Session>('/sessions')]);[this.records,this.events,this.sessions]=result;}
  navigate(view:string){this.view=view;this.menu=false;this.search='';this.selectedEvent=null;void this.perform(async()=>{if(view==='records'||view==='blogs')this.records=await this.api.page<C.Record>('/'+view);if(view==='chronicle'){[this.events,this.templates,this.files,this.records]=await Promise.all([this.api.page<C.Event>('/events'),this.api.page<C.EventTemplate>('/event-templates'),this.api.page<C.File>('/files'),this.api.page<C.Record>('/records')]);}if(view==='insights'){[this.insights,this.evidences,this.observations]=await Promise.all([this.api.page<C.Insight>('/insights'),this.api.page<C.Evidence>('/evidences'),this.api.page<C.Observation>('/observations')]);}if(view==='reflections')this.reflections=await this.api.page<C.Reflection>('/reflections');if(view==='actions')this.actions=await this.api.page<C.Action>('/actions');if(view==='settings')this.usage=await this.api.request('/me/usage');});}
  loginDev(){void this.perform(async()=>{await this.api.request('/auth/dev','POST',{email:this.devEmail,name:'探索者'} satisfies C.DevLogin);await this.api.me();await this.load();});}
  logout(){void this.perform(async()=>{await this.api.request('/auth/logout','POST');this.streamAbort?.abort();this.api.user.set(null);});}
  editRecord(record?:C.Record){this.recordEditor=record?{id:record.id,version:record.version,type:record.type,title:record.title,content:record.content,occurred_at:record.occurred_at}:{type:this.view==='blogs'?'blog':'manual',title:'',content:''};}
  saveRecord(){void this.perform(async()=>{const r=this.recordEditor!;const path=this.view==='blogs'?'/blogs':'/records';if(!r.title.trim()||!r.content.trim())throw new Error('請填寫標題與內容。');const {id,...body}=r;await this.api.request(path+(id?'/'+id:''),id?'PATCH':'POST',body);this.recordEditor=null;this.records=await this.api.page(path);this.notice='已保存這段紀錄。';});}
  editEvent(e?:C.Event){this.eventEditor=e?{id:e.id,version:e.version,title:e.title,description:e.description,event_type:e.event_type,started_at:e.started_at,ended_at:e.ended_at,date_precision:e.date_precision,tags:e.tags,user_verified:e.user_verified}:{title:'',description:'',event_type:'personal',date_precision:'unknown',started_at:null,ended_at:null};}
  saveEvent(){void this.perform(async()=>{const {id,...body}=this.eventEditor!;if(!body.title.trim())throw new Error('請填寫事件名稱。');const e=await this.api.request<C.Event>('/events'+(id?'/'+id:''),id?'PATCH':'POST',body);this.eventEditor=null;this.events=await this.api.page('/events');await this.eventDetails(e);});}
  async eventDetails(e:C.Event){this.selectedEvent=await this.api.request('/events/'+e.id);this.slots=await this.api.page('/events/'+e.id+'/file-slots');}
  openEvent(e:C.Event){void this.perform(()=>this.eventDetails(e));}
  chooseTemplate(id:string){this.templateDraft=this.templates.find(t=>t.id===id)?.slots.map(s=>({...s}))??null;}
  applyTemplate(){void this.perform(async()=>{await this.api.request(`/events/${this.selectedEvent!.id}/template`,'POST',{slots:this.templateDraft!} satisfies C.TemplateApply);this.templateDraft=null;await this.refreshEvent();});}
  async refreshEvent(){await this.eventDetails(this.selectedEvent!);this.events=await this.api.page('/events');}
  addSlot(){void this.perform(async()=>{if(!this.slotName.trim())return;await this.api.request(`/events/${this.selectedEvent!.id}/file-slots`,'POST',{name:this.slotName,status:'PENDING'} satisfies C.SlotCreate);this.slotName='';await this.refreshEvent();});}
  updateSlot(s:C.FileSlot,status:C.FileSlot['status'],fileId?:string){void this.perform(async()=>{await this.api.request(`/events/${this.selectedEvent!.id}/file-slots/${s.id}`,'PATCH',{version:s.version,status,linked_file_id:fileId??null} satisfies C.SlotUpdate);await this.refreshEvent();});}
  removeSlot(s:C.FileSlot){void this.perform(async()=>{await this.api.request(`/events/${this.selectedEvent!.id}/file-slots/${s.id}`,'DELETE');await this.refreshEvent();});}
  addLink(kind:'record'|'file',id:string,remove=false){void this.perform(async()=>{if(!id)return;await this.api.request(`/events/${this.selectedEvent!.id}/links`,remove?'DELETE':'POST',kind==='record'?{record_id:id}:{file_id:id});await this.refreshEvent();});}
  upload(event:Event){const input=event.target as HTMLInputElement;const file=input.files?.[0];if(!file)return;void this.perform(async()=>{if(file.size>50*1024*1024)throw new Error('單一檔案不能超過 50 MiB。');const data=new FormData();data.append('file',file);await this.api.request('/files','POST',data);this.files=await this.api.page('/files');input.value='';this.notice='檔案已上傳，掃描通過後可連結至材料。';});}
  refreshFiles(){void this.perform(async()=>{this.files=await this.api.page('/files'+(this.search?'?q='+encodeURIComponent(this.search):''));});}
  newSession(){void this.perform(async()=>{this.streamAbort?.abort();this.session=await this.api.request<C.Session>('/sessions','POST',{title:'新的探索'});this.messages=[];this.streamText='';this.streamUi=[];this.sessions=await this.api.page('/sessions');});}
  openSession(s:C.Session){if(this.streaming)return;void this.perform(async()=>{this.session=s;this.messages=await this.api.page(`/sessions/${s.id}/messages`);this.streamText='';this.streamUi=[];});}
  async send(text=this.message){if(this.streaming||!text.trim())return;this.error='';try{if(!this.session)this.session=await this.api.request('/sessions','POST',{title:text.slice(0,60)} satisfies C.SessionCreate);const accepted=await this.api.request<C.MessageAccepted>(`/sessions/${this.session!.id}/messages`,'POST',{content:text} satisfies C.MessageCreate,crypto.randomUUID());this.message='';this.messages=await this.api.page(`/sessions/${this.session!.id}/messages`);this.runId=accepted.run_id;this.streamText='';this.streamUi=[];this.streaming=true;this.stage='正在理解';this.streamAbort=new AbortController();this.cdr.markForCheck();await this.api.stream(accepted.stream_url,e=>this.onStream(e),this.streamAbort.signal);this.messages=await this.api.page(`/sessions/${this.session!.id}/messages`);this.streamText='';this.streamUi=[];this.sessions=await this.api.page('/sessions');}catch(e){this.error=this.errorText(e);}finally{this.streaming=false;this.cdr.markForCheck();}}
  onStream(e:C.StreamEvent){if(e.type==='stage.changed')this.stage=String(e.payload['stage']??'探索中');if(e.type==='text.delta')this.streamText+=String(e.payload['text']??e.payload['delta']??'');if(e.type==='ui.ready'){const ui=e.payload['ui']??e.payload['components']??e.payload['component'];this.streamUi.push(...(Array.isArray(ui)?ui:ui?[ui]:[]));}if(e.type==='run.failed')this.error=String(e.payload['message']??e.payload['error']??'生成失敗，已保留你的訊息。');if(e.type==='run.cancelled')this.notice='已停止這次生成。';this.cdr.markForCheck();}
  cancelRun(){void this.perform(async()=>{await this.api.request(`/runs/${this.runId}/cancel`,'POST');});}
  feedback(value:NonNullable<AppComponent['feedbackEditor']>){if(value.decision==='partial'){this.feedbackEditor={...value};return;}void this.perform(()=>this.submitFeedback(value));}
  async submitFeedback(v:NonNullable<AppComponent['feedbackEditor']>){if(v.decision==='partial'&&!v.statement.trim())throw new Error('請填入修正後的理解。');await this.api.request(`/hypotheses/${v.id}/feedback`,'POST',{version:v.version,decision:v.decision,...(v.decision==='partial'?{statement:v.statement}:{})} satisfies C.HypothesisFeedback,crypto.randomUUID());this.feedbackEditor=null;this.notice=v.decision==='agree'||v.decision==='partial'?'已保存你確認的理解。':'已記錄回饋；這個假設不會成為已確認理解。';if(this.session)this.messages=await this.api.page(`/sessions/${this.session.id}/messages`);}
  saveFeedback(){void this.perform(()=>this.submitFeedback(this.feedbackEditor!));}
  why(ids:string[]){void this.perform(async()=>{this.whyItems=await Promise.all([...new Set(ids)].map(id=>this.api.request<C.Evidence>('/evidences/'+id)));this.whyObservations=(await this.api.page<C.Observation>('/observations')).filter(o=>o.evidence_refs.some(id=>ids.includes(id)));this.sourceDetail='';});}
  source(e:C.Evidence){void this.perform(async()=>{const paths={record:'records',event:'events',insight:'insights',reflection:'reflections'};const data=await this.api.request<{title?:string;content?:string;description?:string;statement?:string;current_understanding?:string;version:number}>(`/${paths[e.source_type]}/${e.source_id}`);this.sourceDetail=`目前來源（版本 ${data.version}；引用版本 ${e.source_version}）\n${data.title??''}\n${data.content??data.description??data.statement??data.current_understanding??''}`;});}
  generateReflection(){void this.perform(async()=>{if(!this.session)return;const r=await this.api.request<C.Reflection>(`/sessions/${this.session.id}/artifact`,'POST',undefined,crypto.randomUUID());this.setReflection(r);});}
  setReflection(r:C.Reflection){this.reflectionEditor={...r};this.unknownText=r.unknowns.join('\n');this.actionText=r.actions.join('\n');}
  openReflection(id:string){void this.perform(async()=>this.setReflection(await this.api.request('/reflections/'+id)));}
  saveReflection(confirm=false){void this.perform(async()=>{let r=this.reflectionEditor!;r=await this.api.request<C.Reflection>('/reflections/'+r.id,'PATCH',{version:r.version,question:r.question,core_conflict:r.core_conflict,current_understanding:r.current_understanding,unknowns:this.unknownText.split('\n').filter(Boolean),actions:this.actionText.split('\n').filter(Boolean)} satisfies C.ReflectionUpdate);this.setReflection(r);if(confirm){r=await this.api.request<C.Reflection>(`/sessions/${r.session_id}/artifact`,'PUT',{version:r.version,confirmed:true} satisfies C.ArtifactSave,crypto.randomUUID());this.setReflection(r);}this.reflections=await this.api.page('/reflections');this.notice=confirm?'已確認並保存探索成果。':'已保存草稿。';});}
  toBlog(r:C.Reflection){void this.perform(async()=>{await this.api.request('/reflections/'+r.id+'/blog','POST',undefined,crypto.randomUUID());this.notice='已建立私人文章副本，可至「我的文章」編輯。';});}
  saveInsight(status:C.InsightUpdate['status']='ACTIVE'){void this.perform(async()=>{const i=this.insightEditor!;await this.api.request('/insights/'+i.id,'PATCH',{version:i.version,statement:i.statement,status} satisfies C.InsightUpdate);this.insightEditor=null;this.insights=await this.api.page('/insights');});}
  addAction(title=this.newAction){void this.perform(async()=>{if(!title.trim())return;await this.api.request('/actions','POST',{title,session_id:this.session?.id??null} satisfies C.ActionCreate);this.newAction='';this.actions=await this.api.page('/actions');this.notice='已加入行動清單。';});}
  saveAction(){void this.perform(async()=>{const a=this.actionEditor!;await this.api.request('/actions/'+a.id,'PATCH',{version:a.version,title:a.title,status:a.status,result:a.result} satisfies C.ActionUpdate);this.actionEditor=null;this.actions=await this.api.page('/actions');this.notice='已保存回顧，可作為下次探索的紀錄。';});}
  confirmDelete(){void this.perform(async()=>{const target=this.deleteTarget!;await this.api.request(target.kind==='me'?'/me':`/${target.kind}/${target.id}`,'DELETE');this.deleteTarget=null;if(target.kind==='me'){this.streamAbort?.abort();this.api.user.set(null);this.notice='帳號已停用，線上資料將於 24 小時內清除。';return;}if(target.kind==='files'){this.files=await this.api.page('/files');if(this.selectedEvent)await this.refreshEvent();}else if(target.kind==='events'){this.events=await this.api.page('/events');this.selectedEvent=null;}else this.records=await this.api.page('/'+target.kind);this.notice='已刪除。';});}
  coverage(e:C.Event){return e.total_slots?`${e.available_slots??0} / ${e.total_slots} 份材料`:'尚未定義材料';}
  status(value:string){return ({AVAILABLE:'可使用',PENDING:'待整理',EXPECTED:'預計取得',MISSING:'缺少材料',NOT_REQUIRED:'不需要',ARCHIVED:'已封存',QUARANTINED:'等待掃描',SCANNING:'掃描中',CLEAN:'掃描通過',REJECTED:'檔案被拒絕',FAILED:'掃描失敗',ACTIVE:'目前理解',SUPERSEDED:'歷史版本',WITHDRAWN:'已撤回',NEEDS_REVIEW:'待複核',PLANNED:'已規劃',IN_PROGRESS:'進行中',COMPLETED:'已完成',ABANDONED:'已放下',VALID:'有效來源',STALE:'來源已更新',SOURCE_REMOVED:'來源已移除'} as {[key:string]:string})[value]??value;}
  copyInsight(i:C.Insight){this.insightEditor={...i};} copyAction(a:C.Action){this.actionEditor={...a};}
}
